;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Element",DevComment="")
+GameplayTagList=(Tag="Element.Earth",DevComment="")
+GameplayTagList=(Tag="Element.Fire",DevComment="")
+GameplayTagList=(Tag="Element.Ice",DevComment="")
+GameplayTagList=(Tag="Element.Lightning",DevComment="")
+GameplayTagList=(Tag="Element.Neutral",DevComment="")
+GameplayTagList=(Tag="Status",DevComment="")
+GameplayTagList=(Tag="Status.Blizzard",DevComment="")
+GameplayTagList=(Tag="Status.Burn",DevComment="")
+GameplayTagList=(Tag="Status.Burst",DevComment="")
+GameplayTagList=(Tag="Status.Char",DevComment="")
+GameplayTagList=(Tag="Status.Charge",DevComment="")
+GameplayTagList=(Tag="Status.Conductor",DevComment="")
+GameplayTagList=(Tag="Status.Crystalize",DevComment="")
+GameplayTagList=(Tag="Status.Earthquake",DevComment="")
+GameplayTagList=(Tag="Status.Ember",DevComment="")
+GameplayTagList=(Tag="Status.Energize",DevComment="")
+GameplayTagList=(Tag="Status.Entomb",DevComment="")
+GameplayTagList=(Tag="Status.Explode",DevComment="")
+GameplayTagList=(Tag="Status.Extinguish",DevComment="")
+GameplayTagList=(Tag="Status.Fracture",DevComment="")
+GameplayTagList=(Tag="Status.Freeze",DevComment="")
+GameplayTagList=(Tag="Status.Hypercharge",DevComment="")
+GameplayTagList=(Tag="Status.Lava",DevComment="")
+GameplayTagList=(Tag="Status.Magma",DevComment="")
+GameplayTagList=(Tag="Status.Melt",DevComment="")
+GameplayTagList=(Tag="Status.Overcharge",DevComment="")
+GameplayTagList=(Tag="Status.Shield",DevComment="")
+GameplayTagList=(Tag="Status.Shockwave",DevComment="")
+GameplayTagList=(Tag="Status.Singe",DevComment="")
+GameplayTagList=(Tag="Status.Slow",DevComment="")
+GameplayTagList=(Tag="Status.Smolder",DevComment="")
+GameplayTagList=(Tag="Status.Stagger",DevComment="")
+GameplayTagList=(Tag="Status.Stun",DevComment="")
+GameplayTagList=(Tag="Status.Superheat",DevComment="")
+GameplayTagList=(Tag="Status.Thunderbolt",DevComment="")

